services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - docker
    networks:
      - jenkins-network

  # deployment-target:
  #   image: docker:dind
  #   privileged: true
  #   restart: always
  #   ports:
  #     - "8081:8080" 
  #   networks:
  #     - jenkins-network

networks:
  jenkins-network:

volumes:
  jenkins_home:
